defaults:
  - _self_
  - args: common

dataset:
  filename: ${hydra:runtime.cwd}/dataset/preprocessed_data.csv
  window: 72
  
  channels:
    date: Date time
    data:
      - DEFORMOMETRO INTERNO
      - DEFORMOMETRO ESTERNO
      - DEFORMOMETRO SU SCALA
      - DEFORMOMETRO ESTERNO.1
      - DEFORMOMETRO SU SCALA.1
      - DEFORMOMETRO SU SCALA.2
      - DEFORMOMETRO SU SCALA.3
      - DEFORMOMETRO ESTERNO.2
      - DEFORMOMETRO ESTERNO.3
      - DEFORMOMETRO ESTERNO.4
      - TEL. 0 VERT. SUD DIR. N-S
      - TEL. 0 VERT. SUD DIR. E-O
      - DEFORMOMETRO SULLA SCALA
      - DEFORMOMETRO INTERNO.1
      - DEFORMOMETRO INTERNO.2
      - DEFORMOMETRO INTERNO.3
      - DEFORMOMETRO INTERNO.4
      - DEFORMOMETRO ESTERNO.5
      - DEFORMOMETRO ESTERNO.6
      - DEFORMOMETRO ESTERNO.7
      - DEFORMOMETRO ESTERNO.8
      - DEFORMOMETRO ESTERNO.9
      - DEFORMOMETRO SULLE SCALE
      - DEFORMOMETRO ESTERNO.10
      - DEFORMOMETRO INTERNO.5
      - DEFORMOMETRO INTERNO.6
      - DEFORMOMETRO ESTERNO.11
      - Velocita vento istantanea
      - Direzione vento istantanea
      - Termometro Aria Piano 8
      - Irraggiamento Solare

  splits:
    test:
      dates:
      - from: 17/06/1997
        to: 21/11/1997
      - from: 08/10/2001
        to: 14/03/2002
      - from: 29/01/2006
        to: 30/06/2006
    train:
      dates:
      - from: 01/08/1993
        to: 09/01/1997
      - from: 22/11/1997
        to: 02/05/2001
      - from: 15/03/2002
        to: 23/08/2005
    validation:
      dates:
      - from: 10/01/1997
        to: 16/06/1997
      - from: 03/05/2001
        to: 07/10/2001
      - from: 24/08/2005
        to: 28/01/2006

train:
  batch_size: 32
  lr: 1e-3
  seed: -1
  gpus: 1
  wandb: false


log:
  metrics_each: 100

model:
  transformer:
    decoder_dim: 128
    decoder_depth: 8
    decoder_heads: 6
    decoder_dropout: 0

wandb:
  entity: mlpi
  project: torre-transformer