defaults:
  - _self_
  - args: common
  - dataset: prepost


train:
  batch_size: 32
  lr: 1e-3
  seed: -1
  gpus: 1
  wandb: false

validation:
  batch_size: 32
  interval: 200
  batches: 10

log:
  metrics_each: 100

model:
  transformer:
    decoder_dim: 128
    decoder_depth: 8
    decoder_heads: 6
    decoder_dropout: 0

evaluate:
  model: ""
  dataset: test
  output_folder: ${hydra:runtime.cwd}/results
  batch_size: 32
  batches: 200

wandb:
  entity: mlpi
  project: torre-transformer