dataset:
  filename: ${hydra:runtime.cwd}/dataset/data_nan.csv
  window: 72
  
  channels:
    date: Date time
    data:
      - DEFORMOMETRO INTERNO
      - DEFORMOMETRO ESTERNO
      - DEFORMOMETRO SU SCALA
      - DEFORMOMETRO ESTERNO.1
      - DEFORMOMETRO SU SCALA.1
      - DEFORMOMETRO SU SCALA.2
      - DEFORMOMETRO SU SCALA.3
      - DEFORMOMETRO ESTERNO.2
      - DEFORMOMETRO ESTERNO.3
      - DEFORMOMETRO ESTERNO.4
      - TEL. 0 VERT. SUD DIR. N-S
      - TEL. 0 VERT. SUD DIR. E-O
      - DEFORMOMETRO SULLA SCALA
      - DEFORMOMETRO INTERNO.1
      - DEFORMOMETRO INTERNO.2
      - DEFORMOMETRO INTERNO.3
      - DEFORMOMETRO INTERNO.4
      - DEFORMOMETRO ESTERNO.5
      - DEFORMOMETRO ESTERNO.6
      - DEFORMOMETRO ESTERNO.7
      - DEFORMOMETRO ESTERNO.8
      - DEFORMOMETRO ESTERNO.9
      - DEFORMOMETRO SULLE SCALE
      - DEFORMOMETRO ESTERNO.10
      - DEFORMOMETRO INTERNO.5
      - DEFORMOMETRO INTERNO.6
      - DEFORMOMETRO ESTERNO.11
      - Velocita vento istantanea
      - Direzione vento istantanea
      - Termometro Aria Piano 8
      - Irraggiamento Solare

  splits:
    train:
      dates:
        - from: 01/01/1993
          to: 31/12/1993
        - from: 01/01/1996
          to: 31/12/1997
    test:
      dates:
        - from: 01/01/1993
          to: 31/12/1993

train:
  batch_size: 32
  lr: 1e-3

model:
  transformer:
    decoder_dim: 128
    decoder_depth: 8
    decoder_heads: 6
    decoder_dropout: 0