defaults:
  - channels: channels

name: full
filename: ${hydra:runtime.cwd}/dataset/preprocessed_data.csv
window: 72

splits:
  test:
    stats: ${hydra:runtime.cwd}/config/dataset/stats/train-full.yaml
    dates:
    - from: 22/04/1997
      to: 19/09/1997
    - from: 11/06/2001
      to: 08/11/2001
    - from: 31/07/2005
      to: 31/12/2005
  train:
    stats: ${hydra:runtime.cwd}/config/dataset/stats/train-full.yaml
    dates:
    - from: 01/08/1993
      to: 21/11/1996
    - from: 20/09/1997
      to: 10/01/2001
    - from: 09/11/2001
      to: 01/03/2005
  validation:
    stats: ${hydra:runtime.cwd}/config/dataset/stats/train-full.yaml
    dates:
    - from: 22/11/1996
      to: 21/04/1997
    - from: 11/01/2001
      to: 10/06/2001
    - from: 02/03/2005
      to: 30/07/2005