defaults:
  - channels: channels

name: prepost
filename: ${hydra:runtime.cwd}/dataset/preprocessed_data.csv
window: 72

splits:
  test:
    stats: ${hydra:runtime.cwd}/config/dataset/stats/train-pre.yaml
    dates:
      - from: 22/10/1995
        to: 19/01/1996
      - from: 11/04/1998
        to: 09/07/1998
      - from: 29/09/2000
        to: 31/12/2000
  train:
    stats: ${hydra:runtime.cwd}/config/dataset/stats/train-pre.yaml
    dates:
      - from: 01/08/1993
        to: 23/07/1995
      - from: 20/01/1996
        to: 10/01/1998
      - from: 10/07/1998
        to: 30/06/2000
  validation:
    stats: ${hydra:runtime.cwd}/config/dataset/stats/train-pre.yaml
    dates:
      - from: 24/07/1995
        to: 21/10/1995
      - from: 11/01/1998
        to: 10/04/1998
      - from: 01/07/2000
        to: 28/09/2000
  post:
    stats: ${hydra:runtime.cwd}/config/dataset/stats/post.yaml
    dates:
      - from: 01/01/2002
        to: 01/01/2006
