date: Date time
data:
  - DEFORMOMETRO INTERNO
  - DEFORMOMETRO ESTERNO
  - DEFORMOMETRO SU SCALA
  - DEFORMOMETRO ESTERNO.1
  - DEFORMOMETRO SU SCALA.1
  - DEFORMOMETRO SU SCALA.2
  - DEFORMOMETRO SU SCALA.3
  - DEFORMOMETRO ESTERNO.2
  - DEFORMOMETRO ESTERNO.3
  - DEFORMOMETRO ESTERNO.4
  - TEL. 0 VERT. SUD DIR. N-S
  - TEL. 0 VERT. SUD DIR. E-O
  - DEFORMOMETRO SULLA SCALA
  - DEFORMOMETRO INTERNO.1
  - DEFORMOMETRO INTERNO.2
  - DEFORMOMETRO INTERNO.3
  - DEFORMOMETRO INTERNO.4
  - DEFORMOMETRO ESTERNO.5
  - DEFORMOMETRO ESTERNO.6
  - DEFORMOMETRO ESTERNO.7
  - DEFORMOMETRO ESTERNO.8
  - DEFORMOMETRO ESTERNO.9
  - DEFORMOMETRO SULLE SCALE
  - DEFORMOMETRO ESTERNO.10
  - DEFORMOMETRO INTERNO.5
  - DEFORMOMETRO INTERNO.6
  - DEFORMOMETRO ESTERNO.11
  - Velocita vento istantanea
  - Direzione vento istantanea
  - Termometro Aria Piano 8
  - Irraggiamento Solare
